### ISSUE TITLE
Seg fault on syntax error

### ISSUE THREAD

**Issue by ChinJoshi** [PaperFanz/laser#3]
When trying to assemble a file with a syntax error, laser segfaults, sometimes on the first pass, sometimes on the second pass. 
Note: I compiled with gcc, not clang.

**Comment by PaperFanz** [comment]
Could you include the file you were trying to assemble that resulted in a segfault, so that I can try and reproduce the error?

**Comment by ChinJoshi** [comment]
Yeah, but I've noticed it segfaults on every error, not just the one in this code(line 14):

[bitRis_broke.txt](https://github.com/PaperFanz/laser/files/3727210/bitRis_broke.txt)

**Comment by PaperFanz** [comment]
I believe I've fixed the error- it was actually related to another bug I've been trying to track down on Windows where the terminal output stops at the first error or warning. The issue was that when a file is passed without a containing directory, i.e. `file.asm` rather than `somefolder/file.asm`, strrchr (filename, '/') would return a 1 rather than a null pointer when I used it to strip the leading directories, which would lead to a segfault.
